module.exports = {
  // type: 'postgres',
  // host: process.env.TYPEORM_HOST,
  // port: process.env.TYPEORM_PORT,
  // username: process.env.TYPEORM_USERNAME,
  // password: process.env.TYPEORM_PASSWORD,
  // database: process.env.TYPEORM_DATABASE,
  // logging: process.env.NODE_ENV === 'env' ? true : false,
  // entities: ['dist/**/*.entity{.ts,.js}'],
  // migrations: ['src/database/migrations/*{.js,.ts}'],
  // ssl: false,
  // synchronize: false,
  type: `postgres`,
  url: `postgres://zmxztaetzvjaww:3cd685f85c1b55523dcbce59734f52070ed9b70e45363e9a2b7d64f3cd861d8e@ec2-52-204-213-254.compute-1.amazonaws.com:5432/d2plf4o0fh5p0l`,
  entities: [`${process.env.TYPEORM_ENTITIES}`],
  migrations: [`${process.env.TYPEORM_MIGRATIONS}`],
  cli: { migrationsDir: `${process.env.TYPEORM_MIGRATIONS_DIR}` },
  extra: {
    ssl: {
      rejectUnauthorized: false,
    },
  },
  //   "type": "mysql",
  //   "host": "localhost",
  //   "port": 3306,
  //   "username": "root",
  //   "password": "root",
  //   "database": "test",
  //   "entities": ["dist/**/*.entity{.ts,.js}"],
  //   "synchronize": true
};
