export enum Configuration {
  PORT = 'PORT',
  DATABASE_NAME = 'DATABASE_NAME',
  POSTGRES_DB = 'POSTGRES_DB',
  POSTGRES_PORT = 'POSTGRES_PORT',
  POSTGRES_USER = 'POSTGRES_USER',
  POSTGRES_PASSWORD = 'POSTGRES_PASSWORD',
  POSTGRES_HOST = 'POSTGRES_HOST',
}
