export enum Configuration {
  PORT = 'PORT',
  DATABASE_NAME = 'DATABASE_NAME',
  DATABASE_TYPE = 'DATABASE_TYPE',
  POSTGRES_DB = 'POSTGRES_DB',
  POSTGRES_PORT = 'POSTGRES_PORT',
  POSTGRES_USER = 'POSTGRES_USER',
  POSTGRES_PASSWORD = 'POSTGRES_PASSWORD',
  POSTGRES_HOST = 'POSTGRES_HOST',
  POSTGRES_SCHEMA = 'POSTGRES_SCHEMA',
  SECRECT_SESSION = 'SECRECT_SESSION',
  API_KEY = 'API_KEY',
}
