import { registerAs } from '@nestjs/config';
import {
  CUSTOMERS_PATH,
  DISCOUNTS_PATH,
  EMPLOYESS_PATH,
  PAYMENT_METHODS_PATH,
  PETS_PATH,
  PET_CLASS_PATH,
  PET_TYPES_PATH,
  PRODUCTION_CATEGORIES_PATH,
  PRODUCTION_LINES_PATH,
  PRODUCTS_PATH,
  PROMOTIONS_PATH,
  SALES_PATH,
  SERVICES_PATH,
  SERVICES_SUPPLIES_PATH,
  SHOPPINGS_PATH,
  STORES_PATH,
  TYPE_DOCUMENTS_PATH,
  TYPE_EMPLOYESS_PATH,
  TYPE_SERVICES_PATH,
  VACCINES_PATH,
  VENDORS_PATH,
} from './paths.config';

export default registerAs('config', () => {
  return {
    apiKey: process.env.API_KEY,
    database: {
      name: process.env.DATABASE_NAME,
      port: process.env.PORT,
      //dbType: process.env.DATABASE_TYPE,
    },
    postgres: {
      dbName: process.env.POSTGRES_DB,
      port: parseInt(process.env.POSTGRES_PORT, 10),
      password: process.env.POSTGRES_PASSWORD,
      schema: process.env.POSTGRES_SCHEMA,
      user: process.env.POSTGRES_USER,
      host: process.env.POSTGRES_HOST,
    },
    mysql: {
      dbName: process.env.MYSQL_DB,
      port: parseInt(process.env.MYSQL_PORT, 10),
      password: process.env.MYSQL_PASSWORD,
      schema: process.env.MYSQL_SCHEMA,
      user: process.env.MYSQL_USER,
      host: process.env.MYSQL_HOST,
    },
    paths: {
      customerPath: CUSTOMERS_PATH,
      discountsPath: DISCOUNTS_PATH,
      employessPath: EMPLOYESS_PATH,
      paymentMehodsPath: PAYMENT_METHODS_PATH,
      petClassPath: PET_CLASS_PATH,
      petTypesPath: PET_TYPES_PATH,
      petsPath: PETS_PATH,
      productionCategoriesPath: PRODUCTION_CATEGORIES_PATH,
      productionLinesPath: PRODUCTION_LINES_PATH,
      productsPath: PRODUCTS_PATH,
      promotionsPath: PROMOTIONS_PATH,
      salesPath: SALES_PATH,
      servicesSuppliesPath: SERVICES_SUPPLIES_PATH,
      servicesPath: SERVICES_PATH,
      shoppingsPath: SHOPPINGS_PATH,
      storesPath: STORES_PATH,
      typeDocumentsPath: TYPE_DOCUMENTS_PATH,
      typeEmployessPath: TYPE_EMPLOYESS_PATH,
      typeServicesPath: TYPE_SERVICES_PATH,
      vaccinesPath: VACCINES_PATH,
      vendorsPath: VENDORS_PATH,
    },
  };
});
